# Generated by Django 2.2.7 on 2019-11-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_auto_20191107_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofdepartment',
            name='password',
            field=models.CharField(default='123', max_length=15),
        ),
        migrations.AddField(
            model_name='headofdepartment',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
    ]
