# Generated by Django 2.2.7 on 2019-11-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20191107_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofdepartment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='headofdepartment',
            name='username',
        ),
    ]
