# Generated by Django 2.2.7 on 2019-11-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_auto_20191107_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
