# Generated by Django 2.2.7 on 2019-11-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_auto_20191110_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office_member_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.OfficeMember'),
        ),
    ]
