# Generated by Django 2.2.7 on 2019-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_auto_20191110_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofdepartment',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='officemember',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
