# Generated by Django 2.2.7 on 2019-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_auto_20191112_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='', max_length=15),
        ),
    ]
