# Generated by Django 2.2.7 on 2019-11-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0013_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='headofdepartment',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hod',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='procurement.HeadOfDepartment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='procurement.Member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_member_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='procurement.OfficeMember'),
        ),
    ]
