# Generated by Django 2.2.7 on 2019-11-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_auto_20191114_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofdepartment',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.HeadOfDepartment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_member_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.OfficeMember'),
        ),
    ]
