# Generated by Django 2.2.7 on 2019-11-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_auto_20191118_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_member_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.OfficeMember'),
        ),
    ]
