# Generated by Django 2.2.7 on 2019-11-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_auto_20191118_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_submission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hod_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hod_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='initiation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Member'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='member_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='member_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='procurement_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.ProcurementStage'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='user_department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.UserDepartment'),
        ),
    ]
