# Generated by Django 2.2.7 on 2019-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_auto_20191118_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='sequence_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
