# Generated by Django 2.2.7 on 2019-11-20 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_auto_20191118_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='description',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_of_submission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_required',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hod_confirmation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='initiation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specification', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_of_reference', models.FileField(blank=True, null=True, upload_to='files/')),
                ('scope_of_works', models.FileField(blank=True, null=True, upload_to='files/')),
                ('requisition_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.Details')),
            ],
        ),
    ]
