# Generated by Django 2.2.7 on 2019-11-20 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0021_auto_20191120_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='member_confirmation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
