# Generated by Django 2.2.7 on 2019-11-20 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_auto_20191120_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='requisition_detail_id',
        ),
        migrations.AddField(
            model_name='details',
            name='requisition_description_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.Description'),
        ),
    ]
