# Generated by Django 2.2.7 on 2019-11-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_auto_20191120_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
