# Generated by Django 2.2.7 on 2019-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='estimated_total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
