# Generated by Django 2.2.7 on 2019-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0025_requisition_estimated_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_submission',
            field=models.DateField(),
        ),
    ]
