# Generated by Django 2.2.7 on 2019-11-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_auto_20191122_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='date_of_submission',
            field=models.DateField(null=True),
        ),
    ]
