# Generated by Django 2.2.7 on 2019-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0027_auto_20191122_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
