# Generated by Django 2.2.7 on 2019-11-25 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_officemember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ao_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ao_confirmation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requisition',
            name='reason_for_rejection',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='requisition',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
