# Generated by Django 2.2.7 on 2019-11-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0032_auto_20191125_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOfFunds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_no', models.CharField(max_length=10)),
                ('programme', models.CharField(max_length=30)),
                ('sub_programme', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=20)),
                ('balance_remaining', models.IntegerField()),
                ('req_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='procurement.Requisition')),
            ],
        ),
    ]
